# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'fileutils'
Vagrant.require_version ">= 1.6.0"

$instance_name="cluster-bootstrap"
$instance_ip="172.17.8.2"

$coreos_channel="stable"
$coreos_name="coreos-" + $coreos_channel 
$coreos_version="= 681.2.0"

$virtualbox_gui = false
$virtualbox_memory = 1024
$virtualbox_cpus = 1

Vagrant.configure("2") do |config|

  config.vm.box = $coreos_name
  config.vm.box_version = $coreos_version
  config.vm.box_url = "http://" + $coreos_channel + ".release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

  config.vm.define vm_name = $instance_name do |config|

    config.vm.hostname = vm_name
    config.vm.network :private_network, ip: $instance_ip, autoconfig: false, :name => "vboxnet0"
    config.ssh.insert_key = false

    config.vm.provider :virtualbox do |virtualbox|
      virtualbox.gui = $virtualbox_gui
      virtualbox.memory = $virtualbox_memory
      virtualbox.cpus = $virtualbox_cpus
    end

    config.vm.synced_folder "docker-registry-service", "/var/lib/docker-registry-service", type: "rsync"
    config.vm.synced_folder "../docker-images", "/home/core/docker-images", type: "rsync"

    #Provision userdata with shell
    config.vm.provision :file, :source => "coreos-userdata", :destination => "/tmp/vagrantfile-user-data"
    config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
    config.vm.provision :file, :source => "bin/docker_build.sh", :destination => "/home/core/docker_build.sh"
    config.vm.provision :shell, :inline => "chmod +x /home/core/docker_build.sh", :privileged => true
    config.vm.provision :file, :source => "bin/docker_enter.sh", :destination => "/home/core/docker_enter.sh"
    config.vm.provision :shell, :inline => "chmod +x /home/core/docker_enter.sh", :privileged => true
    config.vm.provision :shell, :inline => "mkdir /home/core/data"
  end
end
