# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'fileutils'
Vagrant.require_version ">= 1.6.0"

###################################################################
##### Configuration ###############################################
##################################################################
$num_instances=5 #number of worker instances

printf("Vagrant configured for %d inaetics workers\n", $num_instances)

Vagrant.configure("2") do |config|
	$coreos_channel="alpha"
	$coreos_name="coreos-" + $coreos_channel 
	$coreos_version=">= 361.0.0"
	config.vm.box = $coreos_name
	config.vm.box_version = $coreos_version
	config.vm.box_url = "http://" + $coreos_channel + ".release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"

	config.vm.synced_folder "inaetics/", "/opt/inaetics"
			
	config.vm.provision :shell, :inline => "ln -s /opt/inaetics/bin /opt/bin", :privileged => true

	(1..$num_instances).each do |i|
	  	config.vm.define vm_name = "worker-#{i}" do |config|

			config.vm.hostname = vm_name
			config.vm.network :private_network, ip: ("172.17.8.%03d" % (i + 100))
			config.ssh.insert_key = false

			config.vm.provider :virtualbox do |virtualbox|
				virtualbox.gui = false
				virtualbox.memory = 1024
				virtualbox.cpus = 1
			end

			#Provision userdata with shell
			config.vm.provision :file, :source => "coreos-userdata", :destination => "/tmp/vagrantfile-user-data"
			config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
		end
	end
end
